services:
  golang-app:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ./:/app/

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.117.0
    command: [ "--config=/etc/otelcol-contrib/config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - '4317:4317'
      - '55679:55679'
