services:
  golang-app:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ./:/app/

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.117.0
    command: [ "--config=/etc/otelcol-contrib/config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "55679:55679"

  autoinstrumenter:
    image: grafana/beyla:2.0.2
    pid: "service:golang-app"
    privileged: true
    environment:
      BEYLA_TRACE_PRINTER: text
      BEYLA_OPEN_PORT: 8080
      OTEL_EXPORTER_OTLP_ENDPOINT: "<your endpoint>"
      GRAFANA_CLOUD_INSTANCE_ID: <your instance ID>
      GRAFANA_CLOUD_API_KEY: "<your access token>"
